include:
  - project: 'metabohub/web-components/mth-cicd'
    ref: 1.0.3
    file: '/templates/npm.gitlab-ci.yml'

.publish:
  before_script:
    - echo "npm run build and other staff before publishing !!"
    #- npm i
    #- npm run build

test-lint:
  image: node:latest
  stage: test
  except:
    - tags
  script:
    - echo "npm lint"
